server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  info:
    env:
      enabled: true

info:
  app: Spring Boot Essentials By DevDojo
  website: https://github.com/0MiniUgo
  github: https://github.com/0MiniUgo/devdojo-springboot-essentials
